version: '2'
services:
  pipeline-app:
    image: pipeline
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pipeline-postgresql:5432/pipeline
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  pipeline-postgresql:
    extends:
      file: postgresql.yml
      service: pipeline-postgresql
