export const enum TaskType {
  SFTP = 'SFTP',

  SHELL = 'SHELL',

  SPARK = 'SPARK',

  SPARK_ON_DATABRICKS = 'SPARK_ON_DATABRICKS',

  SPARK_ON_KUBERNETES = 'SPARK_ON_KUBERNETES',

  SPARK_ON_EMR = 'SPARK_ON_EMR',
}
