export const enum TaskType {
  SFTP = 'SFTP',

  SHELL = 'SHELL',

  SPARK = 'SPARK',

  S3COPY = 'S3COPY',

  S3PUSH = 'S3PUSH',

  SPARK_ON_DATABRICS = 'SPARK_ON_DATABRICS',

  SPARK_ON_KUBERNETES = 'SPARK_ON_KUBERNETES',

  SPARK_ON_EMR = 'SPARK_ON_EMR',
}
